# Credit to:
#https://axdlog.com/2018/using-hugo-and-travis-ci-to-deploy-blog-to-github-pages-automatically/
# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/reference/xenial/
# https://docs.travis-ci.com/user/languages/go/
# https://docs.travis-ci.com/user/customizing-the-build/

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

dist: xenial

language: go

go:
    - 1.12.x

# Only clone the most recent commit.
git:
  submodules: false
  depth: 1

# This is a workaround to trim out my private submodule
before_install:
        - head -n -3 .gitmodules > .gitmodules
        - rm -rf content/zettelkasten
        - cat .gitmodules
        - git submodule update --init --recursive

# before_install
# install - install any dependencies required
install:
    - go get github.com/gohugoio/hugo   # @todo #2:30m/DEV pin the version

before_script:
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  verbose: true
  local-dir: public
  fqdn: bryanapperson.com
  on:
    branch: master  # branch contains Hugo generator code
