baseurl = "https://bryanapperson.com"
title = "Bryan Apperson"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Bryan Apperson"
    info = "Site Reliability Engineer"
    avatarurl = "images/avatar.png"
    footercontent = "All opinions expressed are my own."
    hidecredits = true
    hidecopyright = false
    rtl = false
    commit = "https://github.com/bryanapperson/blog/tree/"
    githubpullurl = true
    custom_css = ["/css/custom.css"]

[taxonomies]
    series = "series"
    tags = "tags"
    categories = "categories"

[params.staticman]
  username = "bryanapperson"
  repository = "blog"
  branch = "master"
  notifications = false

[[params.social]]
    name = "Bryan Apperson's Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/bryanapperson"
[[params.social]]
    name = "Bryan Apperson's Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/bryapperson"
[[params.social]]
    name = "Bryan Apperson's LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/bryan-apperson-1471bb65/"
[[params.social]]
    name = "Sitemap"
    icon = "fas fa-sitemap"
    weight = 3
    url = "sitemap.xml"



# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog/"
