baseurl = "https://bryanapperson.com" # Controls base URL sitewide
languageCode = "en-US" # Controls site language
title = "Bryan Apperson" # Homepage title and page title suffix
paginate = 11 # Number of posts to show before paginating
copyright = "Copyright &copy; Bryan Apperson. Licensed under <a target=\"_blank\" rel=\"external noopener license\" href=\"https://creativecommons.org/licenses/by-nd/4.0/\">CC-BY-ND-4.0</a>." # Optional, remove to suppress copyright notices
canonifyurls = true

# Controls default theme and theme components
theme = [
  "fractal-forest", # OBSD
  "after-dark" # AGPL-3.0-or-later
]

disableLiveReload = false # Optional, set true to disable live reload
enableRobotsTXT = true # Suggested, enable robots.txt file
sectionPagesMenu = "main" # Enable menu system for lazy bloggers

[markup.goldmark.renderer]
  unsafe = true # Optional, allows HTML inside your CommonMark content
[markup.tableOfContents]
  startLevel = 1 # Suggested, draws TOC using all heading levels
  endLevel = 6 # Suggested, draws TOC using all heading levels
[markup.highlight]
  noClasses = false # Suggested, used for custom syntax highlighting

[params]
  description = "" # Suggested, controls default description meta
  author = "Bryan Apperson" # Optional, controls author name display on posts
  commit = "https://github.com/bryanapperson/blog/tree/"
  githubpullurl = true
  custom_css = ["/css/custom.css"]
  avatarurl = "images/avatar.png"
  info = "Site Reliability Engineer"
  hide_author = false # Optional, set true to hide author name on posts
  disable_csp = false # Optional, set true to disable content security policy
  images = [
    "https://source.unsplash.com/collection/983219/2000x1322"
  ] # Suggested, controls default Open Graph images

[params.layout.menu.main]
  hidden = false # Optional, set false or remove to show section menu

[params.layout.footer]
  hidden = false # Optional, set true to hide footer

[params.modules.fractal_forest]
  enabled = true # Optional, set false to disable module
  decoders = ["bpgdec8a"] # Optional, 8-bit javascript decoder with animation

#[params.hackcss]
#  mode = "standard"
#  palette = "light"

# For fuzzy search
# TODO(compare with lunr.js)
[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params.staticman]
  username = "bryanapperson"
  repository = "blog"
  branch = "master"
  notifications = false

[[params.social]]
    name = "Bryan Apperson's Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/bryanapperson"
[[params.social]]
    name = "Bryan Apperson's Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/bryapperson" 
[[params.social]]
    name = "Bryan Apperson's LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/bryan-apperson-1471bb65/"
[[params.social]]
    name = "Sitemap"
    icon = "fas fa-sitemap"
    weight = 3
    url = "sitemap.xml"

[params.layout.home]
  hide_blog = true

[[params.layout.home.section]]
  type = "musings"
  limit = 3
  weight = 3

[[params.layout.home.section]]
  type = "blog"
  limit = 3
  weight = 4

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Resume"
  weight = 2
  identifier = "resume"
        url = "/resume/"
